---
- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20220713170417381300000006.cxddihah2qtf.us-east-2.rds.amazonaws.com"
    login_user: "onyeka"
    login_password: "12345678"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-20220713170417381300000006.cxddihah2qtf.us-east-2.rds.amazonaws.com" }
    - { regexp: '^admin', line: "onyeka" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "12345678" }

